env:
  scenario: vm_scheduling
  topology: azure.2019.10k
  start_tick: 1
  durations: 8638
  resolution: 1
  seed: 666
  state_shaping:
    pm_num: 30
experiment_name: "10k_pm30_epoch_600_experiment"
eval_interval: 10
main_loop:
  max_episode: 600
  exploration:
    parameter_names:
      - "epsilon"
    split_ep: 200
    start_values: 0.4
    mid_values: 0.1
    end_values: 0.0
agents:
  model:
    pm_num: 30
    tick_input_dim: 1
    pm_input_dim: 5
    vm_input_dim: 3
    hidden_dims:
      - 32
      - 64
      - 128
    output_dim: 31   # number of possible actions
    softmax: false
    batch_norm: false
    skip_connection: false
    dropout_p: 0.0
  optimizer:
    lr: 0.0005
  scheduler:
    T_0: 500
    T_mult: 2
  hyper_params:
    reward_discount: 0.2
    min_exp_to_train: 1024
    num_batches: 100
    batch_size: 4096
    target_update_freq: 5
    tau: 0.1
    is_double: true
    per_sample_td_error: true
  seed: 16  # for reproducibility
