decision:
  resolution: 20 # frequence to check if a cell need an action
  effective_time_mean: 20
  effective_time_std: 10
  high_water_mark_ratio: 0.9 # TODO: name
  low_water_mark_ratio: 0.05
trip_adjustment:
  bike_discount: 0.3
  adjust_rate: 1
  adjust_value: 1
reward: # reward options
  alpha: 0.4
  beta: 0.3
  gamma: 0.3
start_datetime: "2019-01-01"
# trip_file: "../../../../bike_pipeline/data/sample/trips.bin"
# cell_file: "../../../../bike_pipeline/data/sample/cell.csv"
# adj_file: "../../../../bike_pipeline/data/sample/map.csv"
# weather_file: "../../../../bike_pipeline/data/sample/weather.npy"
trip_file: "/home/xinran/bike_data/data.bin"
cell_file: "/home/xinran/maro/bike_pipeline/data/sample/cell.csv"
adj_file: "/home/xinran/maro/bike_pipeline/data/sample/map.csv"
weather_file: "/home/xinran/maro/bike_pipeline/data/sample/weather.npy"
