decision:
  resolution: 20 # frequence to check if a cell need an action
  effective_time_mean: 20
  effective_time_std: 10

  # these 2 water mark will affect the if decision should be generated
  high_water_mark_ratio: 0.9
  low_water_mark_ratio: 0.2

  # ratio of action 
  action_scope:
    low: 0.1 # min ratio of available bikes to keep for current cell, to supply to neighbors
    high: 0.6 # max ratio of available bikes neighbors can provide to current cell
trip_adjustment:
  bike_discount: 0.3
  adjust_rate: 1
  adjust_value: 1
reward: # reward options
  alpha: 0.4
  beta: 0.3
  gamma: 0.3
extra_cost_mode: source # source, target, target_neighbors
trip_file: "../../../../bike_pipeline/data/sample/trips.bin"
cell_file: "../../../../bike_pipeline/data/sample/cell.csv"
adj_file: "../../../../bike_pipeline/data/sample/map.csv"
weather_file: "../../../../bike_pipeline/data/sample/weather.npy"
# trip_file: "/home/xinran/bike_data/data.bin"
# cell_file: "/home/xinran/maro/bike_pipeline/data/sample/cell.csv"
# adj_file: "/home/xinran/maro/bike_pipeline/data/sample/map.csv"
# weather_file: "/home/xinran/maro/bike_pipeline/data/sample/weather.npy"
