# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# Create new folders under topologies to maintain your different environment configuration.

# TODO: Add your detailed configuration here, if any.
# You can refer to the yaml config example in the Notebook shared to you.
