# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

job: your_job_name
scenario_path: "/path/to/your/scenario"
log_path: "/path/to/your/log/folder"
main:
  num_episodes: 100
  num_steps: -1
  eval_schedule: 10
  logging:
    stdout: INFO   # DEBUG, INFO, WARN, ERROR, CRITICAL, PROGRESS
    file: DEBUG
rollout:
  parallelism: 10
  eval_parallelism: 1
  min_env_samples: 8
  grace_factor: 0.2
  proxy:   # ignored if parallelism = 1
    host: rollout_proxy
    frontend: 20000
    backend: 20001
  logging:
    stdout: INFO   # DEBUG, INFO, WARN, ERROR, CRITICAL, PROGRESS
    file: DEBUG
training:
  mode: simple  # simple, parallel
  load_path: "/path/to/your/models"
  checkpointing:
    path: "/path/to/your/checkpoint/folder"
    interval: 10
  proxy:   # ignored under simple mode
    host: train_proxy
    frontend: 10000
    backend: 10001
  num_workers: 10
  logging:
    stdout: INFO   # DEBUG, INFO, WARN, ERROR, CRITICAL, PROGRESS
    file: DEBUG