# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

from abc import ABC, abstractmethod
from collections import defaultdict
from os import getcwd
from typing import Dict, List

from maro.rl.policy import AbsPolicy
from maro.utils import Logger


class AbsDecisionGenerator(ABC):
    def __init__(self, agent2policy: Dict[str, str]):
        super().__init__()
        self.agent2policy = agent2policy

    @abstractmethod
    def choose_action(self, state: dict, ep: int, step: int) -> dict:
        """Generate an action based on the given state.
        
        Args:
            state (dict): Dicitionary of agents' states based on which action decisions will be made.
            ep (int): Current episode.
            step (int): Current step.
        """
        raise NotImplementedError


class LocalDecisionGenerator(AbsDecisionGenerator):
    """Local decision generator.

    Args:
        agent2policy (Dict[str, str]): Mapping from agent ID's to policy ID's. This is used to direct an agent's
            queries to the correct policy.
        policies (List[AbsPolicy]): A list of policies for inference.
        log_dir (str): Directory to store logs in. A ``Logger`` will be created at init time and this directory
            will be used to save the log files generated by it. Defaults to the current working directory.
    """
    def __init__(self, agent2policy: Dict[str, str], policies: List[AbsPolicy], log_dir: str = getcwd()):
        super().__init__(agent2policy)
        self.policy_dict = {policy.name: policy for policy in policies}
        self.policy = {agent_id: self.policy_dict[policy_id] for agent_id, policy_id in self.agent2policy.items()}
        self._logger = Logger("local_decision_generator", dump_folder=log_dir)

    def choose_action(self, state: dict, ep: int, step: int) -> dict:
        """Generate an action based on the given state.
        
        Args:
            state (dict): Dicitionary of agents' states based on which action decisions will be made.
            ep (int): Current episode.
            step (int): Current step.
        """
        return {agent_id: self.policy[agent_id].choose_action(st) for agent_id, st in state.items()}

    def store_experiences(self, exp_by_agent: dict) -> set:
        """Store agent experiences in the policies' experience managers."""
        policies_with_new_exp = set()
        for agent_id, exp in exp_by_agent.items():
            self.policy[agent_id].experience_manager.put(exp)
            policies_with_new_exp.add(self.agent2policy[agent_id])

        return policies_with_new_exp

    def get_experiences_by_policy(self, policy_names: List[str]):
        """Get experiences by policy names."""
        return {name: self.policy_dict[name].experience_manager.get() for name in policy_names}

    def update(self, policy_state_dict: dict):
        """Update policy states."""
        for policy_id, policy_state in policy_state_dict.items():
            self.policy_dict[policy_id].set_state(policy_state)

        if policy_state_dict:
            self._logger.info(f"updated policies {list(policy_state_dict.keys())}")
