# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

from collections import defaultdict
from os import getcwd
from typing import Dict

from maro.communication import Proxy
from maro.rl.env_wrapper import AbsEnvWrapper
from maro.rl.exploration import AbsExploration
from maro.utils import Logger

from .decision_generator import AbsDecisionGenerator
from .message_enums import MsgKey, MsgTag


def rollout_worker(
    env: AbsEnvWrapper,
    decision_generator: AbsDecisionGenerator,
    group: str,
    exploration_dict: Dict[str, AbsExploration] = None,
    agent2exploration: Dict[str, str] = None,
    eval_env: AbsEnvWrapper = None,
    log_dir: str = getcwd(),
    **proxy_kwargs
):
    """Roll-out worker process.

    Args:
        env (AbsEnvWrapper): An ``AbsEnvWrapper`` instance to interact with a set of agents and collect experiences
            for policy training / update.
        decision_generator (AbsDecisionGenerator): Source of action decisions which could be local or remote
            depending on the implementation. 
        group (str): Group name for all roll-out workers and the roll-out manager that manages them. The roll-out
            manager process must be assigned this group name in order to form a communicating cluster.
        exploration_dict (Dict[str, AbsExploration]): A set of named exploration schemes. Defaults to None.
        agent2exploration (Dict[str, str]): Mapping from agent ID's to exploration scheme ID's. This is used to direct
            an agent's query to the correct exploration scheme. Defaults to None.
        eval_env (AbsEnvWrapper): An ``AbsEnvWrapper`` instance for policy evaluation. If None, ``env`` will be used
            as the evaluation environment. Defaults to None.
        log_dir (str): Directory to store logs in. A ``Logger`` will be created at init time and this directory
            will be used to save the log files generated by it. Defaults to the current working directory.
        proxy_kwargs: Keyword parameters for the internal ``Proxy`` instance. See ``Proxy`` class
            for details.
    """
    eval_env = eval_env if eval_env else env
    # mappings between exploration schemes and agents
    if exploration_dict:
        exploration_by_agent = {
            agent_id: exploration_dict[exploration_id] for agent_id, exploration_id in agent2exploration.items()
        }
        agent_groups_by_exploration = defaultdict(list)
        for agent_id, exploration_id in agent2exploration.items():
            agent_groups_by_exploration[exploration_id].append(agent_id)

        for exploration_id, agent_ids in agent_groups_by_exploration.items():
            agent_groups_by_exploration[exploration_id] = tuple(agent_ids)

    proxy = Proxy(group, "rollout_worker", {"rollout_manager": 1}, **proxy_kwargs)
    logger = Logger(proxy.name, dump_folder=log_dir)

    def collect(msg):
        ep, segment = msg.body[MsgKey.EPISODE], msg.body[MsgKey.SEGMENT]
        # load policies
        if hasattr(decision_generator, "update"):
            decision_generator.update(msg.body[MsgKey.POLICY])
        # set exploration parameters
        exploration_params = None
        if MsgKey.EXPLORATION in msg.body:
            updated_exploration_param_names = {}
            for exploration_name, param_dict in msg.body[MsgKey.EXPLORATION].items():
                updated_exploration_param_names[exploration_name] = param_dict.keys()
                for param_name, value in param_dict.items():
                    setattr(exploration_dict[exploration_name], param_name, value)

            exploration_params = {
                agent_ids: {
                    param_name: getattr(exploration_dict[exploration_name], param_name)
                    for param_name in updated_exploration_param_names[exploration_name]
                }
                for exploration_name, agent_ids in agent_groups_by_exploration.items()
            }
            logger.info(f"Exploration parameters: {exploration_params}")

        if env.state is None:
            logger.info(f"Training episode {msg.body[MsgKey.EPISODE]}")
            env.reset()
            env.start()  # get initial state

        starting_step_index = env.step_index + 1
        steps_to_go = float("inf") if msg.body[MsgKey.NUM_STEPS] == -1 else msg.body[MsgKey.NUM_STEPS]
        while env.state and steps_to_go > 0:
            action = decision_generator.choose_action(env.state, ep, env.step_index)
            if exploration_dict:
                for agent_id in action:
                    action[agent_id] = exploration_by_agent[agent_id](action[agent_id])
            env.step(action)
            steps_to_go -= 1

        logger.info(
            f"Roll-out finished for ep {ep}, segment {segment}"
            f"(steps {starting_step_index} - {env.step_index})"
        )

        if hasattr(decision_generator, "store_experiences"):
            policy_names = decision_generator.store_experiences(env.get_experiences())
            ret_exp = decision_generator.get_experiences_by_policy(policy_names)

        return_info = {
            MsgKey.EPISODE_END: not env.state,
            MsgKey.EPISODE: ep,
            MsgKey.SEGMENT: segment,
            MsgKey.EXPERIENCES: ret_exp,
            MsgKey.ENV_SUMMARY: env.summary,
            MsgKey.NUM_STEPS: env.step_index - starting_step_index + 1
        }

        proxy.reply(msg, tag=MsgTag.COLLECT_DONE, body=return_info)

    def evaluate(msg):
        logger.info(f"Evaluating...")
        ep = msg.body[MsgKey.EPISODE]
        eval_env.reset()
        eval_env.start()  # get initial state
        if hasattr(decision_generator, "update"):
            decision_generator.update(msg.body[MsgKey.POLICY])
        while eval_env.state:
            action = decision_generator.choose_action(env.state, ep, eval_env.step_index)
            eval_env.step(action)

        return_info = {MsgKey.ENV_SUMMARY: env.summary, MsgKey.EPISODE: msg.body[MsgKey.EPISODE]}
        proxy.reply(msg, tag=MsgTag.EVAL_DONE, body=return_info)

    """
    The event loop handles 3 types of messages from the roll-out manager:
        1)  COLLECT, upon which the agent-environment simulation will be carried out for a specified number of steps
            and the collected experiences will be sent back to the roll-out manager;
        2)  EVAL, upon which the policies contained in the message payload will be evaluated for the entire
            duration of the evaluation environment.
        3)  EXIT, upon which it will break out of the event loop and the process will terminate.

    """
    for msg in proxy.receive():
        if msg.tag == MsgTag.EXIT:
            logger.info("Exiting...")
            proxy.close()
            break

        if msg.tag == MsgTag.COLLECT:
            collect(msg)
        elif msg.tag == MsgTag.EVAL:
            evaluate(msg)