{
 "title": "Citibike Experiment Metric Statistics",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "experiment",
    "label": "Experiment",
    "query": "SHOW TAG VALUES ON \"maro\" WITH KEY = \"experiment\" "
   },
   {
    "name": "episode",
    "label": "Episode",
    "query": "select \"ep\"  from \"bike_shortage\"  WHERE \"experiment\"=~/^$experiment$/"
   },
   {
    "name": "station",
    "label": "Cell",
    "query": "select \"station\"  from \"bike_station_usage\"  WHERE \"experiment\"=~/^$experiment$/"
   },
   {
    "name": "action_tick",
    "label": "Action Tick",
    "query": "select \"tick\" from \"bike_q_value_number\" where \"experiment\" = '$experiment' and \"ep\" = $episode"
   }
  ]
 },
 "panels": [
  { "title": "Overall Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Training Progress",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "dynamic_info",
     "query": "SELECT \"ep_progress\" FROM \"bike_dynamic_info\" WHERE (\"experiment\" =~ /^$experiment$/ AND \"is_train\" = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "current_ep" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "is_train", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Testing Progress",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "dynamic_info",
     "query": "SELECT \"ep_progress\" FROM \"bike_dynamic_info\" WHERE (\"experiment\" =~ /^$experiment$/ AND \"is_train\" = false) AND $timeFilter",
     "select": [
      [
       { "params": [ "current_ep" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "is_train", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "CPU Percent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "targets": [
    {
     "measurement": "bike_dynamic_info",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Percent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "targets": [
    {
     "measurement": "bike_dynamic_info",
     "select": [
      [
       { "params": [ "memory_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Time Cost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "measurement": "bike_time_cost",
     "select": [
      [
       { "params": [ "ep_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Shortage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bike_shortage",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Trip Requirement",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bike_booking",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Fulfillment Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bike_fulfill",
     "select": [
      [
       { "params": [ "total_fulfill" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Business Metrics (All Episodes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Fulfillment Ratio",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "measurement": "bike_fulfill",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Maintain Cost",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "measurement": "bike_tml_cost",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Shortage",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "targets": [
    {
     "measurement": "bike_shortage",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Extra Cost",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 14 },
   "targets": [
    {
     "measurement": "bike_ex_cost",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Business Metrics (Episode $episode)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Shortage in Episode $episode",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "shortage",
     "query": "SELECT  /^[0-9]+$/ FROM \"bike_shortage\" WHERE (\"experiment\" =~ /^$experiment$/ AND \"ep\" = $episode) AND $timeFilter ",
     "select": [
      [
       { "params": [ "demand_port_001" ], "type": "field" }
      ],
      [
       { "params": [ "demand_port_002" ], "type": "field" }
      ],
      [
       { "params": [ "supply_port_001" ], "type": "field" }
      ],
      [
       { "params": [ "supply_port_002" ], "type": "field" }
      ],
      [
       { "params": [ "transfer_port_001" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  },
  {
   "title": "Shortage in Episode $episode",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "measurement": "event_shortage",
     "query": "SELECT * FROM \"bike_event_shortage\" WHERE (\"experiment\" =~ /^$experiment$/ AND \"ep\" = $episode) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  },
  {
   "title": "Cell Cost in Episode $episode",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "measurement": "event_shortage",
     "query": "SELECT * FROM \"bike_event_tml_cost\" WHERE (\"experiment\" =~ /^$experiment$/ AND \"ep\" = $episode) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  },
  {
   "title": "Extra Cost in Episode $episode",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "measurement": "event_shortage",
     "query": "SELECT * FROM \"bike_event_ex_cost\" WHERE (\"experiment\" =~ /^$experiment$/ AND \"ep\" = $episode) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  },
  {
   "title": "Trips Heat Map in Episode $episode",
   "type": "grafana-heatmapchart-panel",
   "gridPos": { "h": 18, "w": 16, "x": 8, "y": 31 },
   "targets": [
    {
     "measurement": "laden_executed",
     "query": "SELECT * FROM \"bike_ride_executed\" WHERE (\"experiment\" =~ /^$experiment$/ AND  \"ep\" = $episode) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  },
  {
   "title": "Cell ($station) Usage in Episode $episode",
   "type": "grafana-stackchart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "measurement": "q_value",
     "query": "SELECT \"bikes\",\"docks\",\"tick\" FROM \"bike_station_usage\" WHERE (\"experiment\" =~ /^$experiment$/ AND  \"ep\" = $episode  and \"station\" = '$station') AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  },
  {
   "title": "Training Metrics (All Episodes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }
  },
  {
   "title": "Loss",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 50 },
   "targets": [
    {
     "measurement": "bike_loss",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Exploration Ratio",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "targets": [
    {
     "measurement": "bike_epsilon",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Time Cost",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 58 },
   "targets": [
    {
     "measurement": "bike_time_cost",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Node Workload",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 58 },
   "targets": [
    {
     "measurement": "bike_dynamic_info",
     "query": "SELECT \"memory_percent\", \"ep\" FROM \"dynamic_info\" WHERE (\"experiment\" =~ /^$experiment$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" }
      ],
      [
       { "params": [ "ep" ], "type": "field" }
      ],
      [
       { "params": [ "memory_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Training Metrics (Episode $episode)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 }
  },
  {
   "title": "Neighbor Q Curve in Episode $episode on Tick $action_tick",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 67 },
   "targets": [
    {
     "measurement": "q_value",
     "query": "SELECT /.policy$/, \"action\" FROM \"bike_q_value_neighbor\" WHERE (\"experiment\" = '$experiment' AND  \"ep\" = $episode AND \"tick\" = $action_tick) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  },
  {
   "title": "Neighbor Q Curve in Episode $episode",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 67 },
   "targets": [
    {
     "measurement": "q_value",
     "query": "SELECT /.policy$/, \"action\" FROM \"bike_q_value_neighbor\" WHERE (\"experiment\" = '$experiment' AND  \"ep\" = $episode) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  },
  {
   "title": "Time Cost in Episode $episode",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 67 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "q_value",
     "query": "SELECT \"other_time\",\"train_time\",\"env_time\" FROM \"bike_time_cost\" WHERE (\"experiment\" = '$experiment' AND  \"ep\" = $episode) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  },
  {
   "title": "Supply Q Curve in Episode $episode on Tick $action_tick",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 75 },
   "targets": [
    {
     "measurement": "q_value",
     "query": "SELECT /.policy$/, \"action\" FROM \"bike_q_value_number\" WHERE (\"experiment\" = '$experiment' AND  \"ep\" = $episode AND \"tick\" = $action_tick) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  },
  {
   "title": "Supply Q Curve in Episode $episode",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 75 },
   "targets": [
    {
     "measurement": "q_value",
     "query": "SELECT /.policy$/, \"action\" FROM \"bike_q_value_number\" WHERE (\"experiment\" = '$experiment' AND  \"ep\" = $episode) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  },
  {
   "title": "Actual Action in Episode $episode",
   "type": "grafana-dotchart-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "measurement": "q_value",
     "query": "SELECT /^actual_action_/, \"tick\" FROM \"bike_actual_action\" WHERE (\"experiment\" = '$experiment' AND  \"ep\" = $episode ) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  }
 ]
}