{
 "title": "Experiment Metric Statistics",
 "time": { "from": "2019-11-22T03:16:14.894Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "experiment",
    "label": "Experiment",
    "query": "SHOW TAG VALUES ON \"maro\" WITH KEY = \"experiment\" "
   },
   {
    "name": "episode",
    "label": "Episode",
    "query": "select \"ep\"  from \"shortage\"  WHERE \"experiment\"=~/^$experiment$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Shortage",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "shortage",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Loss",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "measurement": "loss",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Exploration",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "measurement": "epsilon",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" }
     ]
    }
   ]
  },
  {
   "title": "Shortage on Episode $episode",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "measurement": "shortage",
     "query": "SELECT \"demand_port_001\", \"demand_port_002\", \"supply_port_001\", \"supply_port_002\", \"transfer_port_001\" FROM \"shortage\" WHERE (\"experiment\" =~ /^$experiment$/ AND \"ep\" = $episode) AND $timeFilter",
     "select": [
      [
       { "params": [ "demand_port_001" ], "type": "field" }
      ],
      [
       { "params": [ "demand_port_002" ], "type": "field" }
      ],
      [
       { "params": [ "supply_port_001" ], "type": "field" }
      ],
      [
       { "params": [ "supply_port_002" ], "type": "field" }
      ],
      [
       { "params": [ "transfer_port_001" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  },
  {
   "title": "Q_Curve on Episode $episode",
   "type": "grafana-linechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "measurement": "q_value",
     "query": "SELECT * FROM \"q_value\" WHERE (\"experiment\" =~ /^$experiment$/ AND  \"ep\" = $episode) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  },
  {
   "title": "Laden Heatmap on Episode $episode",
   "type": "grafana-heatmapchart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "measurement": "laden_executed",
     "query": "SELECT * FROM \"laden_executed\" WHERE (\"experiment\" =~ /^$experiment$/ AND  \"ep\" = $episode) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "experiment", "operator": "=~", "value": "/^$experiment$/" },
      { "condition": "AND", "key": "ep", "operator": "=~", "value": "/^$episode$/" }
     ]
    }
   ]
  }
 ]
}